class SecurityRules {
  // Common urgency and phishing triggers
  static const Set<String> phishingKeywords = {
    'login',
    'log-in',
    'signin',
    'sign-in',
    'verify',
    'verification',
    'account',
    'password',
    'passcode',
    'bank',
    'banking',
    'reward',
    'winner',
    'urgent',
    'kyc',
    'payment',
    'refund',
    'otp',
    'claim',
    'suspended',
    'security',
    'wallet',
    'authenticate',
    'invoice',
    'gift',
    'crypto',
    'airdrop',
    'prize',
    'lottery',
    'reactivate',
  };

  // Known URL shortening services that mask final destination
  static const Set<String> urlShorteners = {
    'bit.ly',
    'tinyurl.com',
    't.co',
    'goo.gl',
    'ow.ly',
    'is.gd',
    'buff.ly',
    'cutt.ly',
    'rb.gy',
    'bl.ink',
    'shorturl.at',
    'tiny.cc',
    'v.gd',
    'clck.ru',
    'adf.ly',
    'qr.ae',
    'qrco.de',
    'rebrand.ly',
    'trib.al',
    'lnkd.in',
  };

  // TLDs frequently abused in malicious / phishing campaigns
  static const Set<String> suspiciousTlds = {
    '.xyz',
    '.top',
    '.work',
    '.click',
    '.loan',
    '.buzz',
    '.fit',
    '.surf',
    '.rest',
    '.gq',
    '.tk',
    '.ml',
    '.cf',
    '.ga',
    '.kim',
    '.country',
    '.stream',
    '.download',
    '.racing',
    '.win',
    '.bid',
  };

  // High-profile brands often targeted by look-alike domains
  static const List<String> targetedBrands = [
    'google',
    'paypal',
    'amazon',
    'apple',
    'microsoft',
    'netflix',
    'facebook',
    'instagram',
    'twitter',
    'whatsapp',
    'telegram',
    'sbi',
    'hdfc',
    'icici',
    'axis',
    'paytm',
    'phonepe',
    'binance',
    'coinbase',
    'metamask',
  ];

  // Common homograph character replacements in typosquatting
  static const Map<String, String> lookAlikeMap = {
    '0': 'o',
    '1': 'l',
    'l': 'i',
    'vv': 'w',
    'rn': 'm',
    'cl': 'd',
  };
}
